### PR TITLE
added telephone-line-vc-dir-segment

### PR DESCRIPTION
**Pull request by yilkalargaw**
I added a segment for version control information for buffers like dired, magit, eshell etc... where vc-mode is null.

### CODE REVIEW

**Comment by sebasmonia** [comment]
I tested this on Windows and it seemed to be reeeeeaaally slow.

**Comment by yilkalargaw** [comment]
Yes  I forgot to test it on windows. Will try it out when I find a windows pc. I will see if I could patch it.

**Comment by dbordak** [comment]
Sorry, missed this PR first time around. I'll hold off on merging it until you guys get that issue sorted, though.

**Comment by sebasmonia** [comment]
I tried eval-region and got...

Malformed arglist: (lambda (face) (replace-regexp-in-string 
$  (shell-command-to-string echo "$(basename $(git rev-parse --show-toplevel 2>/dev/null) 2>/dev/null)::$(git rev-parse --abbrev-ref HEAD 2>/dev/null)")))

I think this has something to do with the macro expansion, but my elisp (or lisp in general) are not THAT good :)

**Comment by FrancescoCadei** [comment]
This should work only on unix. Are you in windows?

**Comment by FrancescoCadei** [comment]
Ok should be interesting to get the current magit-project and the current magit-brach.

**Pull request closed without merging**
